name: Rust

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  call-near-workflow:
    uses: convowork1/test-near-pipe/.github/workflows/rust.yml@mail
