name: Rust

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: convowork1/test-near-pipe/.github/workflows/rust.yml@mail
    - name: Build
